name: SemConv

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  lint-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./actions/semconv/pull-request
